In [1]:
import numpy as np
import cv2 as cv

# 항목의 수 
## size 속성을 사용
## (주의) 항목의 수를 구하기 위해 len()함수를 사용할 경우 다차원 배열에서 문제 발생

In [3]:
nums = np.array([1,4,2,6,3])
print(nums)
print(nums.ndim)
print(nums.shape)
print(len(nums.shape))
print(nums.size)

[1 4 2 6 3]
1
(5,)
1
5


# 슬라이싱 
## 배열명[start : stop]
## 배열명[start : stop : step]

In [5]:
nums = np.array([1,2,4,3,2])
print(nums[::2])

[1 4 2]


In [8]:
nums=np.array([[1,4,2],[7,5,2]])
print(nums)

[[1 4 2]
 [7 5 2]]


In [9]:
nums.ndim

2

In [10]:
nums.shape

(2, 3)

In [11]:
len(nums.shape)

2

In [12]:
nums.size

6

In [13]:
len(nums)

2

In [14]:
nums[0,2]

2

In [15]:
nums[0][2]

2

In [17]:
print(nums)

[[1 4 2]
 [7 5 2]]


In [18]:
np.array([[1,4,2],[7,5,3]])
print(nums)

[[1 4 2]
 [7 5 2]]


In [19]:
print(nums[0:1,])

[[1 4 2]]


In [20]:
print(nums[0:1,:])

[[1 4 2]]


In [25]:
print(nums[:,1:2])

[[4]
 [5]]


In [26]:
print(nums[:,1])

[4 5]


In [28]:
print(nums[1:,1:])

[[5 2]]


In [29]:
print(nums[1,1:])

[5 2]


In [31]:
print(nums[1:,1])

[5]


In [33]:
nums[1:,1:2].ndim

2

In [34]:
nums[1:,1].ndim

1

In [36]:
print(nums[:,2:])

[[2]
 [2]]


In [39]:
print(nums[1,:2])

[7 5]


In [40]:
print(nums[1:,:2])

[[7 5]]


In [43]:
np.array(3)

array(3)

In [44]:
nums=np.array(3)
print(nums)

3


In [45]:
print(nums.ndim)

0


In [46]:
print(nums.shape)

()


# Numpy 배열 사용시 주의사항

## 배열에 대한 검색/슬라이싱 결과는 참조만 할당
## 기존 배열이 변경될 경우 값이 같이 변경 됨

## 독립적으로 사용해야할 경우 copy() 함수 사용

In [47]:
nums = np.array([1,4,2,5,3])

In [49]:
ref = nums[1:4]
print(ref)

[4 2 5]


In [50]:
cpy = nums[1:4].copy()
print(cpy)

[4 2 5]


In [51]:
nums[2] = 10

In [52]:
print(ref) # 참조를 하고 있어기 때문에 변경된 값이 반영

[ 4 10  5]


In [54]:
print(cpy) # nums[1:4].copy() 를 이용하면 독립적으로 사용가능

[4 2 5]


In [55]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [56]:
print(np.zeros(2))

[0. 0.]


In [57]:
print(np.ones(1))

[1.]


In [62]:
print(np.ones((1,2)))

[[1. 1.]]


In [63]:
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [65]:
print(np.full((2,2),0))

[[0 0]
 [0 0]]


In [67]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [70]:
np.eye(3,k=3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [73]:
np.random.random((2,2)) # 0 과 1 사이의 임의의 숫자 

array([[0.63229383, 0.27261242],
       [0.1495487 , 0.34673501]])

In [74]:
np.linspace(0,1,num=5,endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [75]:
np.linspace(0,1,num=5,endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [76]:
np.linspace(0,1,num=5,endpoint=False,retstep=True)

(array([0. , 0.2, 0.4, 0.6, 0.8]), 0.2)

In [77]:
np.arange(1,3,1)

array([1, 2])

In [78]:
np.arange(0.4,1.1,0.1)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [79]:
sap=np.array(['mmm','aby','assdf','safsaf','mmm','aby','assdf','safsaf','mmm','aby','assdf','safsaf'])
len(sap.shape)

1

In [80]:
len(sap)

12

In [81]:
sap

array(['mmm', 'aby', 'assdf', 'safsaf', 'mmm', 'aby', 'assdf', 'safsaf',
       'mmm', 'aby', 'assdf', 'safsaf'], dtype='<U6')

In [86]:
a= sap.reshape(3,4)

In [87]:
len(a)

3

In [89]:
a

array([['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf']], dtype='<U6')

In [90]:
len(a)

3

In [91]:
a.size

12

In [92]:
a

array([['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf']], dtype='<U6')

In [93]:
a.T

array([['mmm', 'mmm', 'mmm'],
       ['aby', 'aby', 'aby'],
       ['assdf', 'assdf', 'assdf'],
       ['safsaf', 'safsaf', 'safsaf']], dtype='<U6')

In [95]:
b=sap.reshape(2,3,2)

In [96]:
b

array([[['mmm', 'aby'],
        ['assdf', 'safsaf'],
        ['mmm', 'aby']],

       [['assdf', 'safsaf'],
        ['mmm', 'aby'],
        ['assdf', 'safsaf']]], dtype='<U6')

In [97]:
b.T

array([[['mmm', 'assdf'],
        ['assdf', 'mmm'],
        ['mmm', 'assdf']],

       [['aby', 'safsaf'],
        ['safsaf', 'aby'],
        ['aby', 'safsaf']]], dtype='<U6')

In [101]:
b.transpose(0,2,1)

array([[['mmm', 'assdf', 'mmm'],
        ['aby', 'safsaf', 'aby']],

       [['assdf', 'mmm', 'assdf'],
        ['safsaf', 'aby', 'safsaf']]], dtype='<U6')

In [102]:
x=np.array([1,2,3])
y=np.array([3,2,1])
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [103]:
z=np.array([4,5,6])

In [104]:
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 4 5 6]


In [105]:
grid=np.array([[1,2,3],[4,5,6]])

In [106]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [108]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [110]:
np.vstack([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [111]:
np.hstack([grid,grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [114]:
y=np.array([[9],
         [8]])
grid=np.array([[1,2,3],
              [4,5,6]])

In [117]:
np.hstack([y,grid])

array([[9, 1, 2, 3],
       [8, 4, 5, 6]])

# Split(배열명, 분할 지점의 리스트)

In [120]:

x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])  # 인덱스 3에서 4까지(5전까지)
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [121]:
grid=np.arange(16)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [127]:
grid=grid.reshape((4,4))

In [128]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [132]:
upper,lower = np.split(grid,[2]) #2전 후로 나눔

In [133]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [134]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
grid=np.arange(16).reshape((4,4))

In [138]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [142]:
left,right = np.hsplit(grid,[1]) # 수평으로 스플릿

In [143]:
left

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [144]:
right

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [146]:
a=np.array([0,1,2])
b=np.array([5,5,5])
print(a+b)

[5 6 7]


In [147]:
a*b

array([ 0,  5, 10])

In [148]:
5*b

array([25, 25, 25])

In [149]:
a*5

array([ 0,  5, 10])

In [150]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [151]:
np.eye(4)+0.01

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [152]:
np.eye(4)+0.01*np.ones(4,)

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [153]:
np.ones((4,))

array([1., 1., 1., 1.])

# 브로드캐스팅 규칙

## 1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다
## 2. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다
## 3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다

In [154]:
import numpy as np
M=np.ones((3,2))
a=np.arange(3)
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [155]:
M = np.ones((3,2))
a=np.arange(3)

In [156]:
M.shape

(3, 2)

In [157]:
a.shape

(3,)

In [158]:
a=np.array([0,-1,2])
a

array([ 0, -1,  2])

In [159]:
abs(a)

array([0, 1, 2])

In [161]:
grid=np.array([[1,2,3],
          [4,6,2]])
np.mean(grid)

3.0

In [162]:
np.mean(grid,axis=0)

array([2.5, 4. , 2.5])

In [163]:
np.mean(grid,axis=1)

array([2., 4.])

In [164]:
x=np.array([1,2,3,4,5])
x<3

array([ True,  True, False, False, False])

In [165]:
a>=3

array([False, False, False])

In [166]:
x==3

array([False, False,  True, False, False])

In [167]:
x!=3

array([ True,  True, False,  True,  True])

In [168]:
rng=np.random.RandomState(0)
rng

RandomState(MT19937) at 0x2279EE32440

In [170]:
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [171]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [173]:
np.count_nonzero(x<6) # coount_nonzero() 함수를 통해 True 개수 파악

8

In [175]:
np.sum(x)

54

In [176]:
np.sum(x<6)

8

In [177]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [180]:
np.any(x>8)  # 하나라도 만족하는지

True

In [181]:
np.all(x<6) #모든 값이 조건을 만족하는지

False

In [182]:
np.all(x<6,axis=1)

array([ True, False, False])

In [183]:
np.sum((x>=3)&(x<6))

6

In [189]:
(x>3)&(x<6)

array([[ True, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False]])

In [192]:
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [193]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [203]:
x=np.random.RandomState(0)
x

RandomState(MT19937) at 0x2279EE32C40

In [204]:
x=x.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [205]:
x[x<6]

array([5, 0, 3, 3, 3, 5, 2, 4])