In [1]:
import numpy as np
import cv2 as cv

# 항목의 수 
## size 속성을 사용
## (주의) 항목의 수를 구하기 위해 len()함수를 사용할 경우 다차원 배열에서 문제 발생

In [2]:
nums = np.array([1,4,2,6,3])
print(nums)
print(nums.ndim)
print(nums.shape)
print(len(nums.shape))
print(nums.size)

[1 4 2 6 3]
1
(5,)
1
5


# 슬라이싱 
## 배열명[start : stop]
## 배열명[start : stop : step]

In [3]:
nums = np.array([1,2,4,3,2])
print(nums[::2])

[1 4 2]


In [4]:
nums=np.array([[1,4,2],[7,5,2]])
print(nums)

[[1 4 2]
 [7 5 2]]


In [5]:
nums.ndim

2

In [6]:
nums.shape

(2, 3)

In [7]:
len(nums.shape)

2

In [8]:
nums.size

6

In [9]:
len(nums)

2

In [10]:
nums[0,2]

2

In [11]:
nums[0][2]

2

In [12]:
print(nums)

[[1 4 2]
 [7 5 2]]


In [13]:
np.array([[1,4,2],[7,5,3]])
print(nums)

[[1 4 2]
 [7 5 2]]


In [14]:
print(nums[0:1,])

[[1 4 2]]


In [15]:
print(nums[0:1,:])

[[1 4 2]]


In [16]:
print(nums[:,1:2])

[[4]
 [5]]


In [17]:
print(nums[:,1])

[4 5]


In [18]:
print(nums[1:,1:])

[[5 2]]


In [19]:
print(nums[1,1:])

[5 2]


In [20]:
print(nums[1:,1])

[5]


In [21]:
nums[1:,1:2].ndim

2

In [22]:
nums[1:,1].ndim

1

In [23]:
print(nums[:,2:])

[[2]
 [2]]


In [24]:
print(nums[1,:2])

[7 5]


In [25]:
print(nums[1:,:2])

[[7 5]]


In [26]:
np.array(3)

array(3)

In [27]:
nums=np.array(3)
print(nums)

3


In [28]:
print(nums.ndim)

0


In [29]:
print(nums.shape)

()


# Numpy 배열 사용시 주의사항

## 배열에 대한 검색/슬라이싱 결과는 참조만 할당
## 기존 배열이 변경될 경우 값이 같이 변경 됨

## 독립적으로 사용해야할 경우 copy() 함수 사용

In [30]:
nums = np.array([1,4,2,5,3])

In [31]:
ref = nums[1:4]
print(ref)

[4 2 5]


In [32]:
cpy = nums[1:4].copy()
print(cpy)

[4 2 5]


In [33]:
nums[2] = 10

In [34]:
print(ref) # 참조를 하고 있어기 때문에 변경된 값이 반영

[ 4 10  5]


In [35]:
print(cpy) # nums[1:4].copy() 를 이용하면 독립적으로 사용가능

[4 2 5]


In [36]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [37]:
print(np.zeros(2))

[0. 0.]


In [38]:
print(np.ones(1))

[1.]


In [39]:
print(np.ones((1,2)))

[[1. 1.]]


In [40]:
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [41]:
print(np.full((2,2),0))

[[0 0]
 [0 0]]


In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [45]:
np.eye(3,k=3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [47]:
np.random.random((2,2)) # 0 과 1 사이의 임의의 숫자 

array([[0.10879171, 0.33829006],
       [0.97478208, 0.92052061]])

In [48]:
np.linspace(0,1,num=5,endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
np.linspace(0,1,num=5,endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [50]:
np.linspace(0,1,num=5,endpoint=False,retstep=True)

(array([0. , 0.2, 0.4, 0.6, 0.8]), 0.2)

In [51]:
np.arange(1,3,1)

array([1, 2])

In [52]:
np.arange(0.4,1.1,0.1)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
sap=np.array(['mmm','aby','assdf','safsaf','mmm','aby','assdf','safsaf','mmm','aby','assdf','safsaf'])
len(sap.shape)

1

In [54]:
len(sap)

12

In [55]:
sap

array(['mmm', 'aby', 'assdf', 'safsaf', 'mmm', 'aby', 'assdf', 'safsaf',
       'mmm', 'aby', 'assdf', 'safsaf'], dtype='<U6')

In [56]:
a= sap.reshape(3,4)

In [57]:
len(a)

3

In [58]:
a

array([['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf']], dtype='<U6')

In [59]:
len(a)

3

In [60]:
a.size

12

In [61]:
a

array([['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf'],
       ['mmm', 'aby', 'assdf', 'safsaf']], dtype='<U6')

In [62]:
a.T

array([['mmm', 'mmm', 'mmm'],
       ['aby', 'aby', 'aby'],
       ['assdf', 'assdf', 'assdf'],
       ['safsaf', 'safsaf', 'safsaf']], dtype='<U6')

In [63]:
b=sap.reshape(2,3,2)

In [64]:
b

array([[['mmm', 'aby'],
        ['assdf', 'safsaf'],
        ['mmm', 'aby']],

       [['assdf', 'safsaf'],
        ['mmm', 'aby'],
        ['assdf', 'safsaf']]], dtype='<U6')

In [65]:
b.T

array([[['mmm', 'assdf'],
        ['assdf', 'mmm'],
        ['mmm', 'assdf']],

       [['aby', 'safsaf'],
        ['safsaf', 'aby'],
        ['aby', 'safsaf']]], dtype='<U6')

In [66]:
b.transpose(0,2,1)

array([[['mmm', 'assdf', 'mmm'],
        ['aby', 'safsaf', 'aby']],

       [['assdf', 'mmm', 'assdf'],
        ['safsaf', 'aby', 'safsaf']]], dtype='<U6')

In [67]:
x=np.array([1,2,3])
y=np.array([3,2,1])
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [68]:
z=np.array([4,5,6])

In [69]:
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 4 5 6]


In [70]:
grid=np.array([[1,2,3],[4,5,6]])

In [71]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [74]:
np.vstack([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
np.hstack([grid,grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
y=np.array([[9],
         [8]])
grid=np.array([[1,2,3],
              [4,5,6]])

In [77]:
np.hstack([y,grid])

array([[9, 1, 2, 3],
       [8, 4, 5, 6]])

# Split(배열명, 분할 지점의 리스트)

In [78]:

x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])  # 인덱스 3에서 4까지(5전까지)
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [79]:
grid=np.arange(16)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [80]:
grid=grid.reshape((4,4))

In [81]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [82]:
upper,lower = np.split(grid,[2]) #2전 후로 나눔

In [83]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [84]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
grid=np.arange(16).reshape((4,4))

In [86]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [87]:
left,right = np.hsplit(grid,[1]) # 수평으로 스플릿

In [88]:
left

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [89]:
right

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [90]:
a=np.array([0,1,2])
b=np.array([5,5,5])
print(a+b)

[5 6 7]


In [91]:
a*b

array([ 0,  5, 10])

In [92]:
5*b

array([25, 25, 25])

In [93]:
a*5

array([ 0,  5, 10])

In [94]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [95]:
np.eye(4)+0.01

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [96]:
np.eye(4)+0.01*np.ones(4,)

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [97]:
np.ones((4,))

array([1., 1., 1., 1.])

# 브로드캐스팅 규칙

## 1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다
## 2. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다
## 3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다

In [98]:
import numpy as np
M=np.ones((3,2))
a=np.arange(3)
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [99]:
M = np.ones((3,2))
a=np.arange(3)

In [100]:
M.shape

(3, 2)

In [101]:
a.shape

(3,)

In [102]:
a=np.array([0,-1,2])
a

array([ 0, -1,  2])

In [103]:
abs(a)

array([0, 1, 2])

In [104]:
grid=np.array([[1,2,3],
          [4,6,2]])
np.mean(grid)

3.0

In [105]:
np.mean(grid,axis=0)

array([2.5, 4. , 2.5])

In [106]:
np.mean(grid,axis=1)

array([2., 4.])

In [107]:
x=np.array([1,2,3,4,5])
x<3

array([ True,  True, False, False, False])

In [108]:
a>=3

array([False, False, False])

In [109]:
x==3

array([False, False,  True, False, False])

In [110]:
x!=3

array([ True,  True, False,  True,  True])

In [111]:
rng=np.random.RandomState(0)
rng

RandomState(MT19937) at 0x2322AB88440

In [112]:
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [113]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [114]:
np.count_nonzero(x<6) # coount_nonzero() 함수를 통해 True 개수 파악

8

In [115]:
np.sum(x)

54

In [116]:
np.sum(x<6)

8

In [117]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [118]:
np.any(x>8)  # 하나라도 만족하는지

True

In [119]:
np.all(x<6) #모든 값이 조건을 만족하는지

False

In [120]:
np.all(x<6,axis=1)

array([ True, False, False])

In [121]:
np.sum((x>=3)&(x<6))

6

In [122]:
(x>3)&(x<6)

array([[ True, False, False, False],
       [False, False, False,  True],
       [False,  True, False, False]])

In [123]:
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [124]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [125]:
x=np.random.RandomState(0)
x

RandomState(MT19937) at 0x2322AB88540

In [126]:
x=x.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [127]:
x[x<6]

array([5, 0, 3, 3, 3, 5, 2, 4])

# OpenCV and Matrix 03

# 저장되어 있는 영상데이터를 파일로 저장하기 위해서는 imwrite()함수를 사용함
## bool imwrite(filename, img,params)

# 이미지 타입 확인
## .bmp 로드하기 -흑백으로
## img1 의 type? - numpy.ndarray
## img1의 shape?
## Shape의 len으로 타입 확인 가능

In [128]:
def func1():
    img1=cv.imread('cat.bmp',cv.IMREAD_GRAYSCALE)
    
    if img1 is None:
        print('Image load failed!')
        return
    
    print('type(img1):', type(img1))
    print('img1.shape:', img1.shape)
    
    if len(img1.shape) == 2:
        print('img1 is a grayscale image')
    
    elif len(img1.shape) ==3:
        print('img1 is a truecolor image')
        
    cv.imshow('img1',img1)
    cv.waitKey()
    cv.destroyAllWindows()

func1()

type(img1): <class 'numpy.ndarray'>
img1.shape: (480, 640)
img1 is a grayscale image


In [129]:
matrix = np.zeros((3, 3), dtype=int)
matrix2 = np.ones((3, 3), dtype=int)
mat3 = np.eye(3, dtype=int)


In [130]:
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [131]:
matrix2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [132]:
mat3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [133]:
def func2():
    img1 = np.empty((480,640), np.uint8) #grayscale image
    img2 = np.zeros((480, 640,3),np.uint8) #color image
    img3 = np.ones((480, 640), np.int32) #1's matrix
    img4 = np.full((480,640),0, np.float32) #Fill with 0.0
    
    mat1 = np.array([[11,12,13,14],
                     [21,22,33,24],
                     [31,32,33,34]]).astype(np.uint8)
    
    mat1[0,1] = 100 #element at x=1, y=0
    mat1[2,:] = 200 
    
    print(mat1)
    
func2()

[[ 11 100  13  14]
 [ 21  22  33  24]
 [200 200 200 200]]


# 얕은 복사 (shallow copy)
# 별도로 메모리를 할당하여 사용하려면 => copy() 사용

In [135]:
# 행렬의 복사
def func3():
    img1=cv.imread('cat.bmp')
    
    img2=img1
    img3=img1.copy()
    
    img1[:,:] = (0,255,255) #g+r = yellow
    
    cv.imshow('img1',img1)
    cv.imshow('img2',img2)
    cv.imshow('img3',img3)
    
    cv.waitKey()
    cv.destroyAllWindows()
func3()

In [138]:
# 부분 행렬 추출

def func4():
    img1=cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    
    img2= img1[200:400, 200:400]
    img3 = img1[200:400, 200:400].copy()
    
    img2+=50 
    
    cv.imshow('img1',img1)
    cv.imshow('img2',img2)
    cv.imshow('img3',img3)
    cv.waitKey()
    cv.destroyAllWindows()
    
func4()

# 색상 반전 => 255 - 원래 값
# 부분 행렬 추출 후 반전

In [ ]:
# 행렬 연산하기
def func6():
    mat1 = np.ones((3,4),np.int32) # 1's matrix
    mat2= np.arange(12).reshape(3,4)
    mat3=mat1+mat2
    mat4=mat2 * 2
    
    print('mat1:')
    print(mat1)
    print('mat2:')
    print(mat2)
    print('mat3:')
    print(mat3)
    print