In [1]:
import sys
import cv2 as cv

img = cv.imread('lena512.bmp')

if img is None:
    print('Image load failed!')
    sys.exit()


cv.imshow('image', img)
cv.waitKey()
#Mat imread(const String& filename, int flags=IMREAD_COLOR); flags=>영상 파일불러올시(컬러모드,영상크기 지정)


27

In [2]:
import numpy as np

def func1():
    img1=cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if img1 is None:
        print('failed!')
        return 
    
    print('type(img1) ', type(img1))
    print('img1.shape: ', img1.shape)
    
    if len(img1.shape)==2:
        print('img1 is a grayscale image')
    elif len(img1.shape)==3:
        print('color')
        
    cv.imshow('img1',img1)
    cv.waitKey()
    cv.destroyAllWindows()

func1()

type(img1)  <class 'numpy.ndarray'>
img1.shape:  (512, 512)
img1 is a grayscale image


In [3]:
def func2():
    img1 = np.empty((480,640), np.uint8) #grayscale
    img2 = np.zeros((480,640,3), np.uint8) #color image
    img3 = np.ones((480,640),np.int32) #1's matrix
    img4 = np.full((480,640), 0, np.float32) #fill with 0,0
    
    mat1

In [4]:
def func3():
    img1 = cv.imread('lena512.bmp')
    
    img2=img1
    img3=img1.copy()
    
    img1[:, :]=(0,255,255) #yello (b,g,r) 순
    
    cv.imshow('img1',img1)# =>노랑
    cv.imshow('img2', img2)# =>노랑
    cv.imshow('img3', img3) #=>사진
    cv.waitKey()
    cv.destroyAllWindows()

func3()

In [5]:
def func4():

SyntaxError: unexpected EOF while parsing (<ipython-input-5-a10146f78d83>, line 1)

In [6]:
def func5() #=>반전 시켜보기 255-원래값

SyntaxError: invalid syntax (<ipython-input-6-abfdd1ec171b>, line 1)

In [7]:
#행렬연산
def func6():
    mat1=np.ones((3,4),np.int32)
    mat2=np.arange(12).reshape(3,4)
    mat3=mat1+mat2
    mat4=mat2*2
    print("mat1")
    print(mat1)
    print("mat2")
    print(mat2)
    print("mat3")
    print(mat3)
    print("mat4")
    print(mat4)
    
func6()

mat1
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
mat2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
mat4
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [8]:
#cap.get(...) 현재 열려있는 카메라 장치 또는 동영상 파일로부터 여러가지정보를 받아 오기 위해 사용

In [9]:
cap = cv.VideoCapture(0)
if not cap.isOpened():
    print('failed')
    sys.exit()
    
print("frame width: ", int(cap.get(cv.CAP_PROP_FRAME_WIDTH)))
print("frame height: ", int(cap.get(cv.CAP_PROP_FRAME_HEIGHT)))

frame width:  640
frame height:  480


In [10]:
while True:
    ret, frame= cap.read() 
# ret, frame= cap.read(): Here, cap is assumed to be an OpenCV video capture object (though it isn't defined in the snippet). 
#The read() method reads a frame from the video source (could be a webcam or video file). It returns two values:
# ret (short for 'return'): A boolean value. If a frame is successfully grabbed, it is True, otherwise, it is False.
# frame: The grabbed frame, if any.
    if not ret:
        break
        
    inversed = ~frame #이미지 반전
    
    cv.imshow('frame',frame)
    cv.imshow('inversed', inversed)
    
    if cv.waitKey(10) == 27: #27==ESC key
        break

cv.destroyAllWindows()

In [11]:
cap=cv.VideoCapture('tree.avi')

if not cap.isOpened():
    print('failed')
    sys.exit()
    
print('width',int(cap.get(cv.CAP_PROP_FRAME_WIDTH)))
print('height',int(cap.get(cv.CAP_PROP_FRAME_HEIGHT)))
print('count',int(cap.get(cv.CAP_PROP_FRAME_COUNT)))

fps = cap.get(cv.CAP_PROP_FPS)
print('FPS: ',fps)
delay=round(1000/fps)

failed


SystemExit: 

C:\Users\USER\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3426: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
cap=cv.VideoCapture('tree.avi')

if not cap.isOpened():
    print("failed")
    sys.exit()
#원본동영상 open  
w=round(cap.get(cv.CAP_PROP_FRAME_WIDTH))
h=round(cap.get(cv.CAP_PROP_FRAME_HEIGHT))
fps=cap.get(cv.CAP_PROP_FPS)

fourcc=cv.VideoWriter_fourcc(*'DVIX')
delay=round(1000/fps)

outputVideo=cv.VideoWriter('tree.avi', fourcc, fps, (w,h))
if not outputVideo.isOpened():
    print('failed!')
    sys.exit()
    
while True:
    ret, frame= cap.read() 
    if not ret:
        break
        
    inversed = ~frame #이미지 반전
    outputVideo.write(inversed)
    
    cv.imshow('frame',frame)
    cv.imshow('inversed', inversed)
    
    if cv.waitKey(delay) == 27: #27==ESC key
        break

cv.destroyAllWindows()

In [ ]:
img=np.full((400,400,3),255,np.uint8)

cv.line(img, (50,50),(200,50),(0,0,255))
cv.line(img, (50,100),(200,100),(255,0,255),3)
cv.line(img, (50,150),(200,150),(255,0,0),10)

cv.line(img, (250,50),(350,100),(0,0,255),1,cv.LINE_4)
cv.line(img, (250,70),(350,120),(255,0,255),1,cv.LINE_8)
cv.line(img, (250,90),(350,140),(255,0,0),1,cv.LINE_AA)

cv.arrowedLine(img, (50,200),(150,200),(0,0,255),1)
cv.arrowedLine(img, (50,250),(350,250),(255,0,255),1)
cv.arrowedLine(img, (50,300),(350,300),(255,0,0),1,cv.LINE_8,0,0.05)


cv.imshow('img',img)
cv.waitKey()
cv.destroyAllWindows()

In [ ]:
img = cv.imread('lena512.bmp')
if img is None :
    print('Image load failed!')
    sys.exit()
    
cv.namedWindow('img')
cv.imshow('img',img)

while True:
    keycode = cv.waitKey()
    if keycode == ord('i') or keycode == ord('I'):
        img= ~img
        cv.imshow('img',img)
    elif keycode ==27 or keycode == ord('q') or keycode == ord('Q'):
        break
        
cv.destroyAllWindows()

In [ ]:

def on_mouse(event, x, y, flags, param):
    global oldx, oldy
    
    if event==cv.EVENT_LBUTTONDOWN:
        oldx, oldy = x,y #마지막 위치 업데이트
        print('Event_LBUTTONDOWN: %d %d' %(x,y))
        
    elif event == cv.EVENT_LBUTTONUP:#클릭버튼 떄기
        print('EVENT_LBUTTONUP: %d %d ' %(x,y))
        
    elif event == cv.EVENT_MOUSEMOVE:
        if flags & cv.EVENT_FLAG_LBUTTON: #true 이면 드래깅중
            cv.line(img, (oldx,oldy),(x,y),(0,255,255),2)
            cv.imshow('img',img)
            oldx, oldy = x,y
            
img = cv.imread('lena512.bmp')
    
if img is None:
    print('Image load failed!')
    sys.exit()
        
cv.namedWindow('img')
cv.setMouseCallback('img',on_mouse)
    
cv.imshow('img',img)
cv.waitKey() #키보드 입력시 종료
cv.destroyAllWindows()

In [ ]:
import numpy as np
import cv2 as cv

#트렉바 사용하기 
#사용자가 마우스를 이용하여 트랙바 위치를 조정하면 그에 해당하는 밝기로 영상이 변경됨
def saturated(value):
    if value > 255:
        value=255
    elif value<0:
        value=0
        
    return value

def on_level_change(pos):
    img[:]=saturated(pos*16)
    cv.imshow('image',img)
    
img=np.zeros((400,400),np.uint8)

cv.namedWindow('image')
cv.createTrackbar('level','image',0,16,on_level_change)

cv.imshow('image',img)
cv.waitKey()
cv.destroyAllWindows

In [ ]:
filename='mydata.json'
def writeData():
    name='Jane'
    age=10
    pt1=(100,200)
    scores=(80, 90, 50)
    mat1=np.array([[1.0, 1.5],[2.0,3.2]], dtype=np.float32)
    
    fs=cv.FileStorage(filename, cv.FILE_STORAGE_WRITE)
    
    if not fs.isOpened():
        print('File open failed!')
        return 
    
    fs.write('name',name)
    fs.write('age',age)
    fs.write('point',pt1)
    fs.write('scores',scores)
    fs.write('data',mat1)
    
    fs.release()
    
#데이터 파일을 읽어 오기 위하여 FileStorage 객체를 생성하고 읽기모드로 열어야함
#XML/YAML/JOSN 파일을 읽기 모드로 열면 파일 전체를 분석하여 계층적 구조를 갖는 노드 집합을 구성
#-Node는 이름과 값으로 구성되어 있는 하나의 데이터를 의미
#-특정 이름으로 저장되어 있는 Node에 접근하려면 getNode() 함수 사용

In [ ]:
#데이터 파일 불러오기
def readData():
    fs=cv.FileStorage(filename, cv.FILE_STORAGE_READ)
    
    if not fs.isOpened():
        print('File open failed!')
        return
    
    name = fs.getNode('name').string()
    age=int(fs.getNode('age').real())
    pt1=tuple(fs.getNode('point').mat().astype(np.int32).flatten())
    mat1=fs.getNode('data').mat()
    
    fs.release()
    
    print('name:', name)
    print('age:', age)
    print('point', pt1)
    print('scores:', scores)
    print('data:')
    print(mat1)

In [ ]:
#유용한 기능
#마스크 연산 
#임의의 모양을 갖는 roi 설정을 위하여 일부 행렬 연산 함수에 대하여 마스크 연산을 지원함
#보통 입력 영상과 크기가 같고 깊이가 cv_8u인 마스크 영상을 함께 인자로 전달 받음.
#일반적으로 사람의 눈으로 구분이 쉽도록 픽셀 값을 0 또는 255로 구성된 흑백 영상을 사용한다.

def mask_setTo():
    src = cv.imread('lena512.bmp', cv.IMREAD_COLOR)
    mask = cv.imread('mask_smile.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None or mask is None:
        print('Image load failed!')
        return 
    
    src[mask>0]=(0,255,255) #b,g,r
    #사용된 mask 영상은 중앙에 웃는 얼굴 부분이 흰색 나머지 영역은 픽셀 값에 해당하는 검은 색
    #마스크 영상에서 흰색으로 표시된 영역에 대해서만 영상 픽셀이 노란색으로 설정된 것을 확인 가능
    cv.imshow('src',src)
    cv.imshow('mask',mask)
    cv.waitKey()
    cv.destroyAllWindows()
    
mask_setTo()

In [ ]:
def mask_copyTo():
    src = cv.imread('airplane.bmp',cv.IMREAD_COLOR)
    mask = cv.imread('mask_plane.bmp', cv.IMREAD_GRAYSCALE)
    dst = cv.imread('field.bmp', cv.IMREAD_COLOR)
    #mask는 grayscale 영상으로, 비행기가 있는 위치에서만 픽셀값이 255이고 나머지 영역은 픽셀값이 0
    #dst 영상은 field.bmp 파일에 저장된 들판
    if src is None or mask is None or dst is None:
        print('Image load failed!')
        return 
    
    dst[mask>0]==src[mask>0] 
    #Mask 영상에서 흰색으로 표현된 위치에서만 src 영상의 픽셀값이 dst 영상으로 복사됨
    
    cv.imshow('src',src)
    cv.imshow('dst',dst)
    cv.imshow('mask',mask)
    cv.waitKey()
    cv.destroyAllWindows()
    
mask_copyTo()

In [ ]:
#TickMeter : 연산시작 측정
def time_inverse():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    dst = np.empty(src.shape, dtype=src.dtype)
    
    tm = cv.TickMeter()
    tm.start()
    
    for y in range(src.shape[0]):
        for x in range(src.shape[1]):
            dst[y,x]=255-src[y,x]
            
    tm.stop()
    print('Image inverse implementation took %4.3f ms.' % tm.getTimeMilli())
    
    cv.imshow('src',src)
    cv.imshow('dst', dst)
    cv.waitKey()
    cv.destroyAllWindows()
    
time_inverse()

In [ ]:
# TickMeter: 연산시작 측정
def time_inverse_numpy():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    tm = cv.TickMeter()
    tm.start()

    # Use numpy operation for inversion
    dst = 255 - src

    tm.stop()
    print('Image inverse implementation took %4.3f ms.' % tm.getTimeMilli())

    cv.imshow('src', src)
    cv.imshow('dst', dst)
    cv.waitKey()
    cv.destroyAllWindows()

time_inverse_numpy()


In [ ]:
# TickMeter: 연산시작 측정
def time_inverse_numpy2():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    tm = cv.TickMeter()
    tm.start()

    # Use numpy bitwise NOT operation for inversion
    dst = ~src

    tm.stop()
    print('Image inverse implementation took %4.3f ms.' % tm.getTimeMilli())

    cv.imshow('src', src)
    cv.imshow('dst', dst)
    cv.waitKey()
    cv.destroyAllWindows()

time_inverse_numpy2()

In [12]:
def useful_func():
    img=cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if img is None:
        print('Image load failed!')
        return
    
    sum_img = np.sum(img)
    mean_img=np.mean(img, dtype=np.int32)
    print('Sum: ',sum_img)
    print('Mean: ',mean_img)
    
useful_func()

Sum:  32518590
Mean:  124


In [13]:
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
minVal, maxVal, minPos, maxPos = cv.minMaxLoc(gray)
print('minVal is',minVal, 'at', minPos)
print('maxVal is', maxVal, 'at', maxPos)

minVal is 25.0 at (508, 71)
maxVal is 245.0 at (116, 273)


#Normalization 정규화

In [14]:
src=np.array([[-1,-0.5,0,0.5,1]], dtype=np.float32)
dst=cv.normalize(src, None, 0, 255, cv.NORM_MINMAX, cv.CV_8U)
print('src: ', src)
print('dst: ', dst)

#-1~1 의 실수로 구성된 1x5행렬을 0~255사이의 정수 행렬로 반환하는 경우
#최솟값은 0, 최대값은 255가 되로록 크기를 조정하고, 결과행렬의 타입이 CV_8U가 되도록 변경

src:  [[-1.  -0.5  0.   0.5  1. ]]
dst:  [[  0  64 128 191 255]]


In [15]:
print('round(2.5) is',round(2.5))
print('round(2.51) is',round(2.51))
print('round(3.499) is',round(3.499))
print('round(3.5) is',round(3.5))
#소수점 아래가 0.5보다 크면 올림 작으면 내림. 정확히 0.5일 경우 가장 가까운 짝수로 반올림 수행

round(2.5) is 2
round(2.51) is 3
round(3.499) is 3
round(3.5) is 4


## 영상의 밝기 조절

#### 원소 자료형이 가질 수 있는 값의 범위를 벗어나는 경우 해당 자료형의 최솟값 또는 최댓값으로 원소 값을 설정하는 연산을 OpenCV에서 포화(saturate) 연산이라고 부름.
#### 실제로 영상의 밝기 조절을 구현할 때에는 아래와 같이 포화 연산을 함께 고려한 수식을 사용해야 함.
#### dst(x,y) = saturate(src(x,y)+n)

In [16]:
import numpy as np
import cv2 as cv

In [17]:
def brightness1():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    dst = cv.add(src, 100) #각각 100씩 더한다! (saturate 자동 적용)
    dst2= cv.subtract(src, 100)
    cv.imshow('src',src)
    cv.imshow('dst',dst)
    cv.imshow('dst2',dst2)
    cv.waitKey()
    cv.destroyAllWindows()
    
brightness1()

### 영상의 밝기 조절 직접 구현하기

In [18]:
def brightness2():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    dst = np.empty(src.shape, src.dtype) #사용자가 직접 결과 영상의 픽셀값을 설정하기 위해서는 반드시 적절한 크기와 
                                        #타입의 결과 영상을 미리 생성해야함
    for y in range(src.shape[0]): #이중 for문을 이용해 영상 전체를 스캔할 수 있음
        for x in range(src.shape[1]):
            dst[y,x]=src[y,x]+100  
    
    cv.imshow('src',src)
    cv.imshow('dst',dst)  #=> 결과가 add와 subtract 함수를 사용했을 때와는 다른 기대하지 않은 결과가 나옴
    #why? => dst[y,x]=src[y,x]+100 과정에는 자동으로 saturate 연산, 즉 포화 연산을 지원하지 않기 떄문에 직접 처리해주어야함.
    cv.waitKey()
    cv.destroyAllWindows()
    
brightness2()

In [19]:
def saturated(value): #포화 연산 함수
    if value>255:
        value = 255
    elif value<0:
        value = 0
    return value

def brightness3():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    dst = np.empty(src.shape, src.dtype)
    for y in range(src.shape[0]): 
        for x in range(src.shape[1]):
            dst[y,x]=saturated(src[y,x]+100)  
    
    cv.imshow('src',src)
    cv.imshow('dst',dst)  
    cv.waitKey()
    cv.destroyAllWindows()
    
brightness3()

In [20]:
#트랙바를 이용한 영상의 밝기 조절

def brightness4():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    def update(pos):
        dst = cv.add(src, pos)
        cv.imshow('dst',dst)
        
    cv.namedWindow('dst')
    cv.createTrackbar('Brightness', 'dst', 0, 100, update)
    update(0)
    
    cv.waitKey()
    cv.destroyAllWindows()
    
brightness4()

# Filtering
### 영상에서 원하는 정보만 통과시키고 원치 않는 정보는 걸러내는 작업
### 영상의 필터링은 보통 마스크(mask)라고 부르는 작은 크기의 행렬을 이용

## mask(마스크)

### 필터링의 성격을 정의하는 행렬
### kermel, window라고도 부름
### mask 자체를 filter라고 부르기도 함

## 필터링 연산 방법

### 그림에 표시한 다양한 필터 마스크에서 진한 색으로 표시한 위치는 anchor point(고정점)
### 고정점은 현재 필터링 작업을 수행하고 있는 기준 픽셀 위치를 나타내고, 대부분의 경우 마스크 행렬을 정중앙을 고정점으로 사용
### 연산의 결과는 마스크 행렬의 모양과 원소 값에 의해 결정
#### 마스크 행렬을 어떻게 정의하는가에 따라 영상의 느낌을 바꿈
#### 잡음 제거, 에지 성분만 나타나도록 만드는 등..

### 마스크 행렬의 모든 원소에 대하여 마스크 행렬 원소 값과 같은 위치에 있는 입력 영상 픽셀값을 서로 곱한 후, 그 결과를 모두 더하는 연산

### 마스크 연산의 결과를 출력 영상에서 고정점 위치에 대응되는 픽셀 값으로 설정
### 마스크 행렬 m의 중심이 입력 영상의 (x,y) 좌표 위에 위치 했을 떄 결과 영상의 픽셀 값 g(x,y)는 다음과 같이 연산

### g(x,y) = m(0,0)f(x-1,y-1) + m(1,0)f(x,y-1) + m(2,0)f(x+1,y-1) +
###               m(0,1)f(x-1,y) + m(1,1)f(x,y) + m(2,1)f(x+1,y) +
###               m(0,2)f(x-1,y+1) + m(1,2)f(x,y+1) + m(2,2)f(x+1,y+1) 

## 가장자리 픽셀의 처리

### 가장자리 픽셀에 대해 필터링을 수행할 때에는 특별한 처리가 필요하다. 
#### (가장자리 확장 방식 : Border Types 열거형 상수 사용) BORDER_REFLECT_101(DEFAULT), BORDER_CONSTANT, BORDER_REPLICATE, BORDER_REFLECT)

## filter2D()함수 : 필터 마스크를 사용하는 필터링
## filter2D(src, dst, ddepth, kernel, anchor, delta, bordertype)
### src 영상에 kernel 필터를 이용하여 필터링을 수행하고, 그 결과를 dst에 저장.
### 만약 src인자와 dst 인자에 같은 변수를 지정하면 필터링 결과를 입력 영상에 덮어쓰게 됨



## 엠보싱 필터링
 
### 엠보싱 필터는 입력 영상을 엠보싱 느낌을 나도록 변환                            -1 -1 0
### 보통 입력 영상에서 픽셀 값 변화가 적은 평탄한 영역은 회색으로 설정   -1  0  1   대각선 방향으로 밝아지는 
### 객체의 경계 부분은 좀 더 밝거나 어둡게 설정하면 엠보싱 느낌이 남        0  1  1

### 대각선 방향으로 픽셀 값이 급격하게 변하는 부분에 필터링 수행 시 : 픽셀 값이 0보다 휠씬 크거나 0보다 휠씬 작은 값을 가지게 됨
### 픽셀 값이 크게 바뀌지 않는 평탄한 영역에 필터링 수행 시 : 결과 영상의 픽셀값이 0에 가까운 값을 가지게 됨
### 이를 그대로 화면에 나타낸다면 음수값은 포화연산에 의해 모두 0이 되어 입체감이 줄어든다. 엠보싱 필터를 구현 시 결과 영상에 128을 더하는 것이 좋음

In [21]:
src = cv.imread('field.bmp', cv.IMREAD_GRAYSCALE)

if src is None:
    print('Image loda failed!')
    sys.exit()
    
emboss = np.array([[-1,-1,0],
                  [-1,0,1],
                  [0,1,1]], np.float32)

dst=cv.filter2D(src, -1 ,emboss, delta=128)

cv.imshow('src',src)
cv.imshow('dst',dst)

cv.waitKey()
cv.destroyAllWindows()

## 블러링(Blurring)

### 마치 초점이 맞지 않은 사진처럼 영상을 부드럽게 만드는 필터링 기법 smoothing(스무딩)이라고도 함
### 영상에서 인접한 픽셀 간의 픽셀 값 변화가 크지 않은 경우 부드러운 느낌을 받을 수 있음
### 블러링은 거친 느낌의 입력 영상을 부드럽게 만드는 용도로 사용되기도 하고, 혹은 입력 영상에 존재하는 잡음의 영향을 제거하는 전처리 과정으로 사용됨

### 평균값 필터

#### 입력 영상에서 특정 픽셀과 주변 픽셀들의 산술 평균을 결과 영상 픽셀 값으로 설정하는 필터
#### 평균값 필터에 의해 생성되는 결과 영상은 픽셀 값의 급격한 변화가 줄어들어 날카로운 엣지가 무디어지고 잡음의 영향이 크게 사라지는 효과가 있음

#### 각각의 행렬은 모두 원소 값이 1로 설정되어 있고, 행렬의 전체 원소 개수로 각 행렬 원소 값을 나누는 형태로 표한
#### 평균값 필터는 마스크의 크기가 커지면 커질수록 더욱 부드러운 느낌의 결과 영상을 생성하며, 그 대신 연산량이 크게 증가할 수 있음.

## blur()함수 : 평균값 필터링 수행
### blur(src,dst,ksize,anchor,bordertype) 

In [22]:
#bulurring_mean() 함수는 3x3, 5x5, 7x7 크기의 평균값 필터를 이용하여 영상을 부드럽게 변환하고 출력한다.
# 평균 값 필터의 크기가 커질수록 결과 영상이 더욱 부드럽게 변경됨

def blurring_mean():
    src=cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('failed!')
        return
    
    cv.imshow('src',src)
    
    for ksize in range(3,9,2):
        dst = cv.blur(src, (ksize, ksize))
        
        desc = "Mean : %dx%d" %(ksize,ksize)
        cv.putText(dst, desc, (10,30), cv.FONT_HERSHEY_SIMPLEX,
                  1.0,255,1,cv.LINE_AA)
        
        cv.imshow('dst',dst)
        cv.waitKey()
        
    cv.destroyAllWindows()
    
blurring_mean()

## 가우시안 분포(정규 분포)

### 가우시안 분포는 평균을 중심으로 좌우 대칭의 종 모양을 갖는 확률 분포
### 자연계에서 발생하는 대부분의 사건이 가우시안 분포를 따름
### 평균과 표준 편차에 따라 분포 모양이 결정됨. 표준 편차가 작으면 그래프가 뾰족한 형태, 표준 편차가 크면 완만한 형태
### 영상의 가우시안 필터에서는 주로 평균이 0인 가우시안 분포함수를 사용

### 2차원 가우시안 분포 함수로부터 마스크 행렬을 사용
### 가우시안 분포함수는 연속 함수이지만 이산형의 마스크를 만들기 위해서 x와  y값이 정수인 위치에서만 가우시안 분포 함수 값을 추출하여 마스크를 생성. 이산형의 마스크를 만듬.

### 필터 마스크를 이용하여 마스크 연산을 수행한다는 것은 필터링 대상 픽셀 근처에는 가중치를 크게 줌
### 필터링 대상 픽셀과 멀리 떨어져 있는 주변부에는 가중치를 조금만 주어서 weight average(가중 평균)을 구하는 것과 동일

### 가우시안 필터 마스크가 가중 평균을 구하기 위한 가중치 행렬 역할을 하는 것

### 마스크 연산에 의한 영상 필터링은 마스크 크기가 커짐에 따라 연산량도 함께 증가

### 마스크 행렬 크기가 9x9일 경우 한번의 마스크 연산시 81번의 곱셈 연산이 필요
### 큰 표준 편차 값을 사용하면 마스크 크기도 함께 커지므로 연산 속도 측면에서 부담이 될 수 있음

### 2차원 가우시안 분포함수는 1차원 가우시안 분포 함수의 곱을 분리할 수 있고, 이 특성을 이용하여 가우시안 필터 연산량을 크게 줄일 수 있음. 1차원 1x9 가우시안 마스크 행렬 g와 전치행렬 g^T 를 이용해서 필터링하면 2차원 가우시안 필터 마스크로 한번 필터링한 것과 같은 효과를 얻음. 연산횟수는 18번으로 감소하며 연산량이 크게 줄어 듬을 확인할 수 있음.


## GaussianBlur() 함수 : 가우시안 필터링 수행
### GaussianBlur(src, dst, ksize, sigmaX, sigmaY, borderType)

In [24]:
import cv2 as cv
def blurring_gaussian():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('failed!')
        return 
    
    cv.imshow('src',src)
    
    for sigma in range(1,6):
        dst = cv.GaussianBlur(src, (0,0), sigma)
        
        desc = "Gaussian: sigma = %d" %(sigma)
        cv.putText(dst, desc, (10, 30), cv.FONT_HERSHEY_SCRIPT_SIMPLEX,
                  1.0, 255, 1, cv.LINE_AA)
        
        cv.imshow('dst',dst)
        cv.waitKey()
        cv.destroyAllWindows()

blurring_gaussian()

# 샤프닝 : 영상 날카롭게 하기
## 언샤프 마스크 필터
### sharpening(샤프닝)이란 영상을 날카로운 느낌이 나도록 변경하는 필터링 기법
### 날카로운 느낌의 영상이란? 초점이 잘 맞는 사진처럼 객체의 윤곽이 뚜렷하게 구분되는 영상을 의미
### 이미 촬영된 사진을 초점이 잘 맞는 사진처럼 보이게끔 변경하려면 영상 에지 근방에서 픽셀 값의 명암비가 커지도록 수정해야함
### 샤프닝을 구현하기 위해 블러링도니 영상을 사용함
### 블러링이 적용되어 부드러워진 영상을 활용하여 반대로 날까로운 영상을 생성
### 블러링이 적용된 영상, 즉 날카롭지 않은 영상을 unsharp(언샤프)하다고 말하기도 함

## 언샤프 마스크 필터의 동작 방식
### f(x,y) : 원본 영상, f2(x,y) : 원본영상을 블러링 처리
### g(x,y) = f(x,y) - f2(x,y) 원본 영상 - 블러링 처리 영상 (날카로운 성분만을 가지고 있는 함수)
### h(x,y) = f(x,y) + a * g(x,y) 샤프닝 된 영상 = 원본영상 + g(x,y) (날카로운 성분만을 가지고 있는 함수)
### a : 가중치, 실수 가중치를 곱한 후 더하면 날카로운 정도를 사용자가 조절 가능
### a<1.0 : 조금 덜 날카로운 영상 a = 1.0 그대로
### OpenCV는 함수를 따로 제공하고 있지 않음

In [3]:
import cv2 as cv
### 영상을 다양한 표준 편차 값으로 가우시안 필터를 적용하고, 블러링된 영상을 이용하여 샤프닝 결과 영상을 생성
### src 창에 나타난 영상은 입력 영상이고, dst 창에 나타난 영상은 다양한 sigma 값에 의해 생성된 언샤프 마스크 필터링 결과
### dst 영상이 경계 부분이 좀 더 뚜렷하게 구분이 되는 것을 확인 가능
### but, sigma 값이 커짐에 따라 다소 과장된 느낌의 샤프닝 결과 영상이 만들어질 가능성을 주의

src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
if src is None:
    print('Image load failed!')
    sys.exit()

cv.imshow('src',src)

for sigma in range(1, 6):
    blurred = cv.GaussianBlur(src, (0,0), sigma)
    
    alpha = 1.0
    dst = cv.addWeighted(src, 1+alpha, blurred, -alpha, 0.0)
    
    desc = "sigma: %d" % sigma
    cv.putText(dst, desc, (10,30), cv.FONT_HERSHEY_SIMPLEX, 1.0, 255, 1, cv.LINE_AA)
    
    cv.imshow('dst',dst)
    cv.waitKey()
cv.destroyAllWindows()

# 잡음 제거 필터링
## 영상과 잡음 모델


In [1]:
import cv2 as cv
import numpy as np
def noise_gaussian():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    cv. imshow('src',src)
    
    for stddev in [10,20,30]:
        noise = np.zeros(src.shape,np.int32)
        cv.randn(noise, 0, stddev)
        
        dst=cv.add(src, noise, dtype=cv.CV_8UC1)
        
        desc = 'stddev = %d' %stddev
        cv.putText(dst, desc, (10,30), cv.FONT_HERSHEY_SIMPLEX,
                  1.0, 255, 1, cv.LINE_AA)
        cv.imshow('dst',dst)
        cv.waitKey()
    cv.destroyAllWindows()

In [2]:
noise_gaussian()

# 양방향 필터

In [3]:
def filter_bilateral():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    noise = np.zeros(src.shape, np.int32)
    cv.randn(noise ,0, 5)
    cv.add(src, noise, src, dtype = cv.CV_8SC1)
    
    dst1 = cv.GaussianBlur(src, (0,0), 5)
    dst2 = cv.bilateralFilter(src, -1, 10, 5)
    
    cv.imshow('src', src)
    cv.imshow('dst1', dst1)
    cv.imshow('dst2', dst2)
    cv.waitKey()
    cv.destroyAllWindows()

In [4]:
filter_bilateral()

# 미디언 필터
## 입력 영상에서 자기 자신 픽셀과 주변 픽셀 값 중에서 중간 값(median)을 선택하여 결과 영상 픽셀 값으로 설정하는 필터링 기법
## 마스크 행렬과 입력 영상 픽셀 값을 서로 곱한 후 모두 더하는 형태의 연산을 사용하지 않음
### 주변 픽셀 값들의 중간 값을 선택하기 위해 내부에서 픽셀값 정렬 과정이 사용됨
## 미디언 필터는 특히 잡음 픽셀 값이 주변 픽셀 값과 큰 차이가 있는 경우에 효과적으로 동작함

## 영상에 추가되는 잡음 중에 salt & pepper noise(소금&후추 잡음)은 픽셀값이 일정 확률로 0 또는 255로 변경되는 형태의 잡음
## salt&pepper? => 잡음이 마치 소금과 후추 처럼 흰색 또는 검은 색으로 구성되기 때문
## 소금 & 후추 잡음이 추가된 영상에 미디언 필터를 적용하면 대부분 소금 & 후추 잡음이 아닌 원본 영상에 존재하는 픽셀값이 중간값으로 선택되기 때문에 잡음은 효과적으로 제거됨

In [10]:
import random
def filter_median():
    src = cv.imread('lena512.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return 
    
    for i in range(0, int(src.size /10)):
        x= random.randint(0, src.shape[1]-1)
        y= random.randint(0, src.shape[0]-1)
        src[x,y]=(i%2)*255
        
    dst1=cv.GaussianBlur(src, (0,0),1)
    dst2=cv.medianBlur(src, 3)
    
    cv.imshow('src',src)
    cv.imshow('dst1',dst1)
    cv.imshow('dst2',dst2)
    cv.waitKey()
    cv.destroyAllWindows()

In [11]:
filter_median()

# 어파인 변환 (affine Transformation)

영상을 평행 이동시키거나 회전, 크기 변환 등을 통해 만들 수 있는 변환을 통칭
영상을 한쪽 방향으로 밀어서 만든 것 같은 전단 변환도 어파인 변환에 포함
직선은 그대로 직선으로 나타나고, 직선 간의 길이 비율과 평행 관계가 그대로 유지됨

직사각형 형태의 영상은 어파인 변환에 의해 평행사변형에 해당하는 모양으로 변경됨



입력 영상과 어파인 변환 결과 영상으로부터 어파인 변환 행렬을 구하기 위해서는 최소 세점의 이동 관계를 알아야 함
점 하나의 이동 관계로부터 x,y 좌표에 대한 변환 수식 두개를 얻을 수 있으므로, 점 세개의 이동 관계로부터 총 여섯개의 방적식을 구할 수 있음.
점 세 개의 이동 관계를 알고 있다면 여섯 개의 원소로 정의되는 어파인 변환 행렬을 구할 수 있음


In [6]:
import numpy as np
import cv2 as cv

def affine_transform():
    src = cv.imread('lena512.bmp')
    
    if src is None:
        print('failed!')
        return 
    
    rows = src.shape[0]
    cols = src.shape[1]
    
    src_pts = np.array([[0,0],
                       [cols-1,0],
                       [cols-1,rows-1]]).astype(np.float32)
    
    dst_pts = np.array([[50,50],
                       [cols-100,100],
                       [cols-50,rows-50]]).astype(np.float32)
    
    affine_mat = cv.getAffineTransform(src_pts, dst_pts)
    dst = cv.warpAffine(src, affine_mat, (0,0))
    
    cv.imshow('src',src)
    cv.imshow('dst',dst)
    cv.waitKey()
    cv.destroyAllWindows()

In [7]:
affine_transform()

# affine_translation() 이동 변환
잘린 부분이 생긴다

In [12]:
def affine_translation():
    src = cv.imread('lena512.bmp')
    
    if src is None:
        print('failed')
        return
    
    affine_mat = np.array([[1,0,150],
                           [0,1,100]]).astype(np.float32)
    
    dst = cv.warpAffine(src, affine_mat, (0,0))
    
    cv.imshow('src',src)
    cv.imshow('dst',dst)
    cv.waitKey()
    cv.destroyAllWindows()

In [13]:
affine_translation()

# 전단 변환

# 크기 변환

# 회전 변환 (rotation transformation)

## 특정 좌표를 기준으로 영상을 원하는 각도만큼 회전하는 변환

## 영상의 회전 변환에 의해 입력 영상의 점 (x,y)가 이동하는 점의 좌표(x',y')는 다음과 같이 삼각함수를 이용하여 구할 수 있음

## x' = cos